[tox]
envlist = black, mypy, py3

[testenv]
skip_install = true
deps = -r requirements-dev.txt

[testenv:black]
commands = black --check --diff .

[testenv:mypy]
commands = mypy

[testenv:py3]
commands = pytest tests/unit -q
